name: agenda_treinamento_web
description: "Agenda de Treinamento - Aplicativo Flutter para gerenciar treinamentos auditivos."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Utilitários
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  table_calendar: ^3.1.2

  # Dependências do Firebase (Conjunto de versões compatíveis)
  firebase_core: ^3.15.0 #^2.27.0
  cloud_firestore: ^5.6.9 #^4.15.8
  firebase_auth: ^5.6.0 #^4.17.8
  cloud_functions: ^5.6.0 #^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 #^3.0.0

flutter:
  uses-material-design: true
